#!/bin/bash
############### Config ###############
#
ssh2Threads=500
port=22
ssSpeed=9
ssh2Timeout=3
############## Running ##############
rm -rf scan.log session.txt
echo "############################"
echo "# GOOD for ROOTs and USERs #"
echo "############################"
././scaneste1 $1 $port > bscan.txt
sleep 2
./scaneste2 $ssh2Threads $port $ssh2Timeout unlimited
